services:
  nextnet-api:
    image: ghcr.io/greysoh/api:latest
    container_name: nextnet-api
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000

  # NOTE: For this to work correctly, the nextnet-api must be version > 0.1.1
  # or have a version with backported username support, incl. logins
  nextnet-lom:
    image: ghcr.io/greysoh/nextnet-ssh:latest
    container_name: nextnet_api
    restart: always
    ports:
      - 2222:2222
    volumes:
      - ssh_key_data:/app/keys

  postgres:
    image: postgres:15.4
    container_name: nextnet-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  ssh_key_data: