services:
  nextnet:
    build:
      context: "."
      dockerfile: Dockerfile
    image: nextnet/latest
    container_name: nextnet-api
    restart: always
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@nextnet-postgres:5432/${POSTGRES_DB}?schema=nextnet"

  postgres:
    image: "postgres:15.4"
    container_name: nextnet-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: